# Generated by Django 4.2 on 2023-04-30 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('correct_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wrong_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='options',
            name='Sual',
        ),
        migrations.AddField(
            model_name='options',
            name='questions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sual', to='quiz.questions'),
            preserve_default=False,
        ),
    ]
