# Generated by Django 4.2 on 2023-06-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_rename_question_questions_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.quiz')),
            ],
        ),
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.AlterField(
            model_name='option',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz.question'),
        ),
    ]
