# Generated by Django 4.2 on 2023-06-06 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_rename_options_option_delete_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='questions',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
    ]
